minimum_pre_commit_version: "3.7.0"
default_stages: [pre-commit]
exclude: ^(node_modules/|dist/|build/|coverage/|\.venv/|venv/|package-lock\.json$|poetry\.lock$)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        files: ^\.github/.*\.ya?ml$

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: ^(src/|tests/).+\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: ["--fix","--exit-non-zero-on-fix"]
        files: ^(src/|tests/).+\.py$

  - repo: local
    hooks:
      - id: prettier-local
        name: prettier (local)
        entry: npx --yes prettier --write
        language: system
        files: ^(README\.md|\.github/.*\.ya?ml|eslint\.config\.mjs)$
