blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/CoderDeltaLAN/ci-matrix-starter/security/advisories/new
    about: Please report security issues privately.
