name: OpenSSF Scorecard
on:
  schedule:
    - cron: "30 1 * * 3"
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write
  security-events: write

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
