name: auto-approve
on:
  workflow_dispatch:
    inputs:
      pr:
        description: PR number to approve
        required: true
  pull_request_target:
    types: [opened, ready_for_review, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNum = (context.eventName === 'workflow_dispatch')
              ? Number(core.getInput('pr'))
              : context.payload.pull_request.number;
            core.info(`Approving PR #${prNum}`);
            await github.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/reviews', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNum,
              event: 'APPROVE'
            });
