name: Auto-approve
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to approve"
        required: true
permissions:
  pull-requests: write
jobs:
  approve:
    name: Approve PR
    runs-on: ubuntu-latest
    steps:
      - name: Approve via API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR: ${{ inputs.pr_number }}
        run: |
          set -euo pipefail
          curl -sS -X POST \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${REPO}/pulls/${PR}/reviews" \
            -d '{"event":"APPROVE"}'
          echo "Approved PR #${PR} as github-actions[bot]"
