name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ping:
    name: ping • ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - run: echo "ok"

  py:
    name: "py / ${{ matrix.python }} • ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.11", "3.12"]
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - name: Preflight
        run: python -V && pip -V
      - name: Install (best-effort)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "no requirements.txt"
          fi
      - name: Lint/Test smoke (best-effort)
        run: |
          python -c "print('python ok')"
          if command -v pytest >/dev/null 2>&1; then pytest -q || true; else echo "pytest not installed"; fi
