name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ping:
    name: ping • ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - run: echo "ok"
