name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ts:
    uses: ./.github/workflows/ts-ci.yml
  py:
    uses: ./.github/workflows/py-ci.yml
    with:
      python-versions: '["3.11","3.12"]'
      cov-min: 100
  build:
    name: build
    runs-on: ubuntu-latest
    needs: [ts, py]
    steps:
      - run: echo "aggregate"
