name: Auto-merge Dependabot when green

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-automerge:
    name: enable-automerge
    # Solo si el PR es de dependabot o si el actor es dependabot
    if: >
      (github.event.pull_request.user.login == 'dependabot[bot]') ||
      (github.actor == 'dependabot[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: Find PR for this context (fallback when dispatched)
        id: find
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;

            // Si viene de PR, úsalo directo
            if (context.payload.pull_request) {
              return { number: context.payload.pull_request.number };
            }

            // Si viene de check_suite/completed o dispatch, intenta localizar el PR abierto en la misma rama
            const head = (context.ref || '').replace('refs/heads/','');
            if (!head) return {};
            const { data: prs } = await github.rest.pulls.list({
              owner, repo, state: 'open', head: `${owner}:${head}`
            });
            const pr = prs.find(p => p.user.login === 'dependabot[bot]');
            return pr ? { number: pr.number } : {};

      - name: Enable auto-merge (squash) if checks are green
        if: steps.find.outputs.result != ''
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const { number } = JSON.parse(process.env.PR_JSON || steps.find.outputs.result);
            const { data: pr } = await github.rest.pulls.get({ owner, repo, pull_number: number });

            // Habilitar auto-merge por GraphQL (requiere node_id)
            await github.graphql(
              `mutation($pull: ID!) {
                 enablePullRequestAutoMerge(input: { pullRequestId: $pull, mergeMethod: SQUASH }) { clientMutationId }
               }`,
              { pull: pr.node_id }
            );

            core.info(`Auto-merge habilitado para PR #${number}`);
