name: Publish container to GHCR (badge)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1"
permissions:
  contents: read
jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ghcr publish badge ✅"
