name: Python CI (reusable)
on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read

jobs:
  badge:
    uses: CoderDeltaLAN/ci-matrix-starter/.github/workflows/py-ci.yml@main
    with:
      os: '["ubuntu-latest"]'
      python_versions: '["3.12"]'
      run_tests: false
