name: py-ci (reusable)
on:
  workflow_call:
  workflow_call:
    inputs:
      python-versions:
        required: false
        type: string
        default: '["3.11","3.12"]'
      cov-min:
        required: false
        type: number
        default: 100
jobs:
  py:
    name: Python ${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py: ${{ fromJson(inputs.python-versions) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - run: pipx install poetry
      - run: poetry install --only main,test --no-interaction
      - run: poetry run ruff check .
      - run: poetry run black --check src tests
      - run: PYTHONPATH=src poetry run pytest -q
