name: "Python CI (reusable)"

on:
  workflow_call:
    inputs:
      python_versions:
        type: string
        required: false
        default: '["3.11","3.12"]'
      os:
        type: string
        required: false
        default: '["ubuntu-latest"]'
      run_tests:
        type: boolean
        required: false
        default: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    name: py${{ matrix.python }} • ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ${{ fromJson(inputs.python_versions) }}
        os: ${{ fromJson(inputs.os) }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [[ -f pyproject.toml ]]; then
            pip install -e ".[dev]" || true
          fi
          pip install ruff black pytest mypy
      - name: Lint
        shell: bash
        run: |
          ruff check .
          black . --check
          mypy || true
      - name: Tests
        if: inputs.run_tests == true
        env:
          PYTHONPATH: src
        shell: bash
        run: |
          pytest -q || rc=$?
          if [[ "${rc:-0}" -eq 5 ]]; then
            echo "No tests collected; treating as success."
            rc=0
          fi
          exit "${rc:-0}"
