name: release-sbom
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Generate SBOM (CycloneDX JSON)
        uses: anchore/sbom-action@c73dd3f93ab542b7902df62a6ee5ad763179fa7b
        with:
          path: .
          format: cyclonedx-json
          output-file: sbom-cyclonedx.json
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
      - name: Sign SBOM (keyless OIDC)
        run: |
          cosign sign-blob --yes \
            --output-signature sbom-cyclonedx.json.sig \
            --output-certificate sbom-cyclonedx.json.crt \
            sbom-cyclonedx.json
      - name: Attach SBOM to release
        uses: softprops/action-gh-releasecbd405e2c4e67a21c47fa9e383d020e4@e28b836
        with:
          files: |
            sbom-cyclonedx.json
            sbom-cyclonedx.json.sig
            sbom-cyclonedx.json.crt
