name: SLSA provenance
on:
  release: { types: [published] }
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
jobs:
  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    permissions:
      contents: write
      id-token: write
    with:
      base64-subjects: "${{ github.sha }}"
