name: SLSA provenance

on:
  push:
    tags:
      - "v*"
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  id-token: write
  attestations: write

concurrency:
  group: slsa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2
    with:
      upload-assets: true
