name: SLSA provenance
on:
  release:
    types: [published]
permissions:
  contents: write
  id-token: write
jobs:
  provenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
        with:
          base64-subjects: "${{ github.sha }}"
