name: SLSA provenance
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  attest-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # usa el ref desde el que se dispare (rama o tag)
          ref: ${{ github.ref_name }}

      - name: Descargar SBOMs del release
        env:
          TAG: ${{ github.event.release.tag_name || github.ref_name }}
        run: |
          mkdir -p dist
          gh release download "$TAG" -p '*sbom*.json' -p '*cyclonedx*.json' -D dist

      - name: Publicar attestation (SLSA)
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "dist/**"
