name: supply-chain
on:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "23 4 * * 1"
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: supply-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sbom:
    name: Generate SBOM (CycloneDX)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          output-file: sbom.cdx.json
      - uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: sbom.cdx.json
  vuln-gate:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
    name: Vulnerability scan (PR gate)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@v0.33.1
        with:
          scan-type: fs
          format: sarif
          output: trivy.sarif
          ignore-unfixed: true
          severity: CRITICAL
          exit-code: "1"
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif
