name: supply-chain
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  sbom:
    name: Generate SBOMs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: SBOM (CycloneDX JSON)
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          output-file: sbom.cdx.json

  weekly:
    name: Weekly gates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Python gates
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --no-interaction
          poetry run ruff check .
          poetry run black --check .
          PYTHONPATH=src poetry run pytest -q
          poetry run mypy src || true
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Node/TS gates (only if package.json exists)
        if: ${{ hashFiles('package.json') != '' }}
        env:
          CI: "true"
        run: |
          npm ci --ignore-scripts --no-audit --no-fund
          npx prettier -c .
          npx eslint . --max-warnings=0
          npx tsc --noEmit || true
          npm test --silent || echo "no tests"
